# Generated by Django 4.2.2 on 2023-06-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
        ('account', '0002_userable_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userable',
            name='interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='interests', to='util.interest'),
        ),
    ]
