# Generated by Django 4.2.2 on 2023-07-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userable_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='post_num',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='rating_sum',
        ),
        migrations.RemoveField(
            model_name='userable',
            name='interest',
        ),
        migrations.AddField(
            model_name='userable',
            name='name',
            field=models.CharField(default='', max_length=16),
        ),
    ]
