# Generated by Django 4.2.2 on 2023-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_employer_post_num_remove_employer_rating_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='age',
            field=models.IntegerField(default='20'),
        ),
        migrations.AddField(
            model_name='employer',
            name='image',
            field=models.ImageField(null=True, upload_to='company_profile/'),
        ),
    ]
