# Generated by Django 4.2.2 on 2023-07-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_employer_age_employer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('남자', 'male'), ('여자', 'female'), ('없음', '없음')], max_length=10),
        ),
    ]
