# Generated by Django 4.2.2 on 2023-07-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_applicant_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='career',
            field=models.ImageField(null=True, upload_to='applicant_career/'),
        ),
        migrations.AlterField(
            model_name='userable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
