# Generated by Django 4.2.2 on 2023-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_applicant_career_alter_userable_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
