# Generated by Django 4.2.2 on 2023-06-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employ_post',
            fields=[
                ('postable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employ.postable')),
                ('required_num', models.IntegerField()),
                ('start_date', models.DateTimeField(max_length=20)),
                ('end_date', models.DateTimeField(max_length=20)),
                ('prefer_condition', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='post/employ/')),
                ('career', models.CharField(choices=[('a', '경력'), ('b', '신입')], default='a', max_length=1)),
            ],
            bases=('employ.postable', models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('postable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employ.postable')),
                ('employ_post_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employ.employ_post')),
            ],
            bases=('employ.postable', models.Model),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('postable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employ.postable')),
                ('progress', models.CharField(max_length=10)),
                ('question_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employ.question')),
            ],
            bases=('employ.postable', models.Model),
        ),
    ]
