# Generated by Django 4.2.2 on 2023-07-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0002_postable_userable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_post',
            name='image',
            field=models.ImageField(null=True, upload_to='post/employ/'),
        ),
    ]
