# Generated by Django 4.2.3 on 2023-07-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0003_alter_employ_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freepost_e',
            fields=[
                ('postable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employ.postable')),
            ],
            bases=('employ.postable', models.Model),
        ),
        migrations.RenameField(
            model_name='postable',
            old_name='post_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='employ_post',
            name='apply_method',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employ_post',
            name='employ_shape',
            field=models.CharField(choices=[('a', '인턴'), ('b', '정규직'), ('c', '비정규직')], default='a', max_length=1),
        ),
    ]
