# Generated by Django 4.2.3 on 2023-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0004_freepost_e_rename_post_title_postable_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postable',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
