# Generated by Django 4.2.3 on 2023-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0005_alter_postable_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default=1, upload_to='post/question'),
            preserve_default=False,
        ),
    ]
