# Generated by Django 4.2.3 on 2023-07-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0006_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='progress',
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(default=1, upload_to='post/answer'),
            preserve_default=False,
        ),
    ]
