# Generated by Django 4.2.3 on 2023-07-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0007_remove_answer_progress_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='progress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
