# Generated by Django 4.2.3 on 2023-07-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0008_question_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost_e',
            name='image',
            field=models.ImageField(default=1, upload_to='post/free_post_e'),
            preserve_default=False,
        ),
    ]
