# Generated by Django 4.2.2 on 2023-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0009_freepost_e_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_post',
            name='career',
            field=models.CharField(choices=[('경력', '경력'), ('경력', '신입')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='employ_post',
            name='employ_shape',
            field=models.CharField(choices=[('인턴', '인턴'), ('정규직', '정규직'), ('비정규직', '비정규직')], default='a', max_length=100),
        ),
    ]
