# Generated by Django 4.2.2 on 2023-07-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0010_alter_employ_post_career_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_post',
            name='apply_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employ_post',
            name='career',
            field=models.CharField(choices=[('경력', '경력'), ('경력', '신입')], default='a', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employ_post',
            name='employ_shape',
            field=models.CharField(choices=[('인턴', '인턴'), ('정규직', '정규직'), ('비정규직', '비정규직')], default='a', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employ_post',
            name='end_date',
            field=models.DateTimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employ_post',
            name='prefer_condition',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employ_post',
            name='required_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employ_post',
            name='start_date',
            field=models.DateTimeField(max_length=20, null=True),
        ),
    ]
