# Generated by Django 4.2.2 on 2023-07-09 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('util', '0002_rating_userinterest_employerrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='userable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest', to=settings.AUTH_USER_MODEL),
        ),
    ]
