# Generated by Django 4.2.2 on 2023-06-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freepost',
            fields=[
                ('postable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employ.postable')),
            ],
            bases=('employ.postable', models.Model),
        ),
        migrations.CreateModel(
            name='Job_post',
            fields=[
                ('postable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employ.postable')),
                ('image', models.ImageField(upload_to='post/job/')),
            ],
            bases=('employ.postable', models.Model),
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(choices=[('a', '사기/도배'), ('b', '욕설/비하')], default='a', max_length=1)),
                ('postable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employ.postable')),
            ],
        ),
    ]
