# Generated by Django 4.2.2 on 2023-07-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_employer_rating_employer_post_num_and_more'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_DEFAULT, to='account.employer'),
        ),
        migrations.AddField(
            model_name='job_post',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
