# Generated by Django 4.2.3 on 2023-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_post_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='search_company',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
