# Generated by Django 4.2.3 on 2023-07-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_post_search_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
