# Generated by Django 4.2.3 on 2023-07-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0009_freepost_e_image'),
        ('job', '0007_alter_report_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freepost_j',
            fields=[
                ('postable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employ.postable')),
                ('image', models.ImageField(upload_to='free_post_j')),
            ],
            bases=('employ.postable',),
        ),
        migrations.RemoveField(
            model_name='job_post',
            name='employer',
        ),
        migrations.DeleteModel(
            name='Freepost',
        ),
    ]
