# Generated by Django 4.2.2 on 2023-07-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_freepost_j_remove_job_post_employer_delete_freepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='employ_shape',
            field=models.CharField(choices=[('인턴', '인턴'), ('정규직', '정규직'), ('비정규직', '비정규직')], default='a', max_length=100),
        ),
    ]
